entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

http:
  middlewares:
    test-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

certificatesResolvers:
  myresolver:
    acme:
      email: mimach.dev@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false
